/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e237f7219450f16d209322f4a0661da4)
interface __BaseEnv_Env {
  REPORT_WORKFLOW: DurableObjectNamespace<import('./src/index').ReportWorkflow>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
    durableNamespaces: 'ReportWorkflow';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
